### ISSUE TITLE
28. CSS 画扇形/三角形

### ISSUE THREAD

**Issue by fedono** [fedono/fe-questions#29]
```css
.effect {
    width: 0;
    height: 0;
    border: solid 100px red;
    border-color: red transparent transparent transparent;
    border-radius: 100px; //  没有border-radius 就是三角形了 
}
```

设置`width/height` 为0，然后设置`border`的宽度，也为三角形的宽度，`border-color` 设置其中一个为具体的颜色，其他的都是空白`transparent` 。设置三角形的方向就是设置`border-color` 为哪一个有颜色即可。
